FROM php:8.0.2-fpm

#RUN apt-get update && apt-get install -y \
#    curl

WORKDIR /var/www
COPY --from=composer:2.9.5 /usr/bin/composer /usr/bin/composer

COPY . .
RUN composer install --prefer-dist --no-dev --no-scripts --no-progress --no-interaction