name: Deploy
on:
  push:
    branches: 
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v1
      -
        name: run composer
        uses: nick-zh/composer-php@master
        with:
         action: 'install -oa' #or alternative dependency management
      - run: vendor/bin/phpunit tests 
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./nginx//Dockerfile
          push: true
          tags: stefanfischer84/taschenrechner:latest
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./php/Dockerfile
          push: true
          tags: stefanfischer84/taschenrechner:latest
        
