 
name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    -
     steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-python@v3
     - uses: pre-commit/action@v3.0.1   
     - uses: nick-zh/composer-php@master
       with:
         action: 'install -oa --dev' #or alternative dependency management
     - run: vendor/bin/phpunit tests 

